############################################################
# Project: Variant Prioritization in Family-Based WES Data
# Dataset: Focal Epilepsy Whole Exome Sequencing Cohort
############################################################

###############################
# STEP 1: Load Variant Table
###############################

# Read annotated variant table generated by SnpEff/SnpSift
variants <- read.table(
  "variant_table.csv",
  header = TRUE,
  sep = "\t",
  fill = TRUE,
  quote = "",
  comment.char = ""
)

###############################
# STEP 2: Initial Exploration
###############################

# Number of rows and columns
dim(variants)

# Column names
colnames(variants)

# Preview first few variants
head(variants)

# Check data structure
str(variants)

# Count variants by annotation effect
table(variants$ANN.0..EFFECT)

###############################
# STEP 3: Functional Variant Filtering
###############################

# Keep variants that are more likely to affect
# protein sequence or RNA splicing

functional <- subset(
  variants,
  grepl(
    "missense|frameshift|stop_gained|stop_lost|start_lost|splice",
    ANN.0..EFFECT
  )
)

# Number of functional variants
nrow(functional)

# Number of unique genes affected
length(unique(functional$ANN.0..GENE))

###############################
# STEP 4: High-Impact Variant Filtering
###############################

# Keep only variants with potentially severe effects

high_impact <- subset(
  variants,
  grepl(
    "frameshift|stop_gained|stop_lost|start_lost|splice_acceptor|splice_donor",
    ANN.0..EFFECT
  )
)

# Number of high-impact variants
nrow(high_impact)

# Number of genes carrying high-impact variants
length(unique(high_impact$ANN.0..GENE))

# Top genes with most high-impact variants
head(
  sort(
    table(high_impact$ANN.0..GENE),
    decreasing = TRUE
  ),
  30
)

###############################
# STEP 5: Search Known Epilepsy Genes
###############################

# List of epilepsy-associated genes

epilepsy_genes <- c(
  "SCN1A",
  "SCN2A",
  "SCN8A",
  "DEPDC5",
  "NPRL3",
  "NPRL2",
  "GABRA1",
  "GABRB3",
  "STXBP1",
  "KCNQ2",
  "KCNQ3",
  "KCNT1",
  "LGI1",
  "PCDH19"
)

# Extract high-impact variants located in epilepsy genes

epilepsy_hits <- high_impact[
  high_impact$ANN.0..GENE %in% epilepsy_genes,
]

epilepsy_hits

###############################
# STEP 6: Load Visualization Package
###############################

library(ggplot2)

###############################
# STEP 7: Variant Prioritization Funnel
###############################

# Summary of filtering process

funnel <- data.frame(
  Stage = factor(
    c(
      "All Variants",
      "Functional Variants",
      "High-Impact Variants",
      "NPRL3 Variants"
    ),
    levels = c(
      "All Variants",
      "Functional Variants",
      "High-Impact Variants",
      "NPRL3 Variants"
    )
  ),
  Count = c(
    423991,
    21740,
    1041,
    3
  )
)

ggplot(funnel, aes(x = Stage, y = Count)) +
  geom_col() +
  geom_text(aes(label = Count), vjust = -0.3) +
  scale_y_log10() +
  expand_limits(y = max(funnel$Count) * 2) +
  labs(
    title = "Variant Prioritization Workflow",
    x = "",
    y = "Number of Variants (log10 scale)"
  ) +
  theme_minimal()

###############################
# STEP 8: Top 10 Variant Effects
###############################

# Most common functional consequences

top_effects <- as.data.frame(
  sort(
    table(variants$ANN.0..EFFECT),
    decreasing = TRUE
  )[1:10]
)

colnames(top_effects) <- c(
  "Effect",
  "Count"
)

ggplot(
  top_effects,
  aes(
    x = reorder(Effect, Count),
    y = Count
  )
) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Top 10 Variant Effects",
    x = "Variant Effect",
    y = "Count"
  ) +
  theme_minimal()

###############################
# STEP 9: Top Genes with
# High-Impact Variants
###############################

top_genes <- sort(
  table(high_impact$ANN.0..GENE),
  decreasing = TRUE
)[1:15]

top_genes_df <- data.frame(
  Gene = names(top_genes),
  Count = as.numeric(top_genes)
)

ggplot(
  top_genes_df,
  aes(
    x = reorder(Gene, Count),
    y = Count
  )
) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Top Genes with High-Impact Variants",
    x = "Gene",
    y = "Number of High-Impact Variants"
  ) +
  theme_minimal()

###############################
# STEP 10: Extract NPRL3 Variants
###############################

# NPRL3 is a known epilepsy-associated gene

nprl3_variants <- high_impact[
  high_impact$ANN.0..GENE == "NPRL3",
]

# Keep only key columns

nprl3_table <- nprl3_variants[, c(
  "CHROM",
  "POS",
  "REF",
  "ALT",
  "ANN.0..GENE",
  "ANN.0..EFFECT"
)]

# Preview candidate variants

nprl3_table

###############################
# STEP 11: Export Final Results
###############################

write.csv(
  nprl3_table,
  "NPRL3_candidate_variants.csv",
  row.names = FALSE
)

############################################################
# End of Analysis
############################################################